export const tasks = [
  {
    id: 1,
    title: 'Ttitle 1',
    text: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    priority: 'A',
    date: '03.02.2024',
    status: 'done',
  },
  {
    id: 2,
    title: 'Title 2',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    priority: 'B',
    date: '03.02.2024',
    status: 'inProgress',
  },
  {
    id: 3,
    title: 'Title 3',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    priority: 'C',
    date: '04.02.2024',
    status: 'new',
  },
  {
    id: 4,
    title: 'Title 4',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    priority: 'A',
    date: '04.02.2024',
    status: 'new',
  },
  {
    id: 5,
    title: 'Title 5',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    priority: 'B',
    date: '04.02.2024',
    status: 'inProgress',
  },
  {
    id: 6,
    title: 'Title 6',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    priority: 'C',
    date: '04.02.2024',
    status: 'done',
  },
  {
    id: 7,
    title: 'Title 7',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    priority: 'A',
    date: '04.02.2024',
    status: 'new',
  },
];
